kind: pipeline
name: deploiement
steps:

  - name: maven build
    image: maven:3.8.4-openjdk-17
    environment:
      SONARHOST:
        from_secret: sonar_host
      SONARLOGIN:
        from_secret: sonar_token
    commands:
      - mvn clean  verify sonar:sonar -Dsonar.host.url=$SONARHOST -Dsonar.login=$SONARLOGIN
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp target/BackendMineralcontest.war .

  - name: copy files into server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /var/lib/tomcat9/webapps/
      source:
        - BackendMineralcontest.war
      script:
        - chown tomcat:tomcat /var/lib/tomcat9/webapps/BackendMineralcontest.war
        - systemctl restart tomcat9
