kind: pipeline
name: deploiement

steps:
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
    port: 22
    script:
      - echo "hello world"
    when:
      branch:
        - master
      event:
        - pull_request