kind: pipeline
name: deploiement
steps:

  - name: maven build
    image: maven:3.8.4-openjdk-17
    environment:
      sonar_host:
        from_secret: sonar_host
      sonar_login:
        from_secret: sonar_token

    commands:
      - mvn sonar:sonar -Dsonar.host.url=${sonar_host} -Dsonar.login=${sonar_token}
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp target/backendMineralcontest-*.war .
      - mv backendMineralcontest-*.war backendMineralcontest.war

  - name: code analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token

  - name: copy files into server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /var/lib/tomcat9/webapps/
      source:
        - backendMineralcontest-*.war