kind: pipeline
name: deploiement
steps:
  - name: maven build
    image: maven:3.8.4-openjdk-17
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - cp target/backendMineralcontest-*.war .

  - name: copy files into server
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: /root
      source:
        - backendMineralcontest-*.war