kind: pipeline
name: deploiement

steps:
  - name: test
    image: maven:3-jdk-17
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
    port: 22
    script:
      - echo "hello world"
    when:
      branch:
        - master
      event:
        - push